import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { SideText } from '../components/SideText/SideText'

const Home: NextPage = () => {

    const title: string = "Home";

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <SideText title={title} />

            <main className={styles.main}>
            </main>

        </div>
    )
}

export default Home
